# Generated by Django 3.2.5 on 2022-02-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Data',
        ),
    ]
